ARG CORE_IMAGE_TAG
FROM php:${CORE_IMAGE_TAG}

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apk add --no-cache --update php8-pecl-xdebug


