#controllers_write:
#  resource: '../src/Write/*'
#  prefix: /api
#  name_prefix: api_
#
#controllers_read:
#  resource: '../src/Read/*'
#  prefix: /api
#  name_prefix: api_

api_register_account:
  path: /api/accounts
  methods: POST
  controller: App\Write\RegisterAccount\Presentation\RegisterAccountController::register
#WRITE

#READ

kernel:
  resource: ../src/Kernel.php
  type: annotation
